#The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# What is the value of the first triangle number to have over five hundred divisors?
'''
1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
'''

from EulerProject_HanFunctions import numDiv
from EulerProject_HanFunctions import numDiv2

element=1
numberOfDiv=1
sumElement=1
while (numberOfDiv < 500):
    element +=1
    sumElement = sumElement + element
    numberOfDiv=numDiv(sumElement)
print "1+2+3+... all the way to ", element, "is", sumElement, "which has", numberOfDiv, "divisors."

# For Python, numDiv1 vs numDiv2 makes a very big difference...

