#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#1. Let's genearate Fibonacci numbers below 4,000,000

fibo1 = 1
fibo2 = 2
fibo3 = 3
sum = fibo2
N = 4000000
while fibo3 <= N:
   fibo1=fibo2
   fibo2=fibo3
   fibo3 = fibo1 + fibo2
   if (fibo2%2==0):
       sum =sum + fibo2
print fibo2, sum

